disqusShortname: dannyguo
googleAnalytics: UA-90320718-1
languageCode: en-us
pygmentsCodefences: true
pygmentsStyle: monokai
title: Danny Guo

outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true

outputs:
  home:
    - HTML
    - RSS
    - Algolia

params:
  sourceCodeRepo: https://github.com/dguo/dguo.github.io/blob/master
