[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.40"

[context.production.environment]
  HUGO_ENV = "production"

[[redirects]]
  from = "/blood-moon"
  to = "https://www.blood-moon.dannyguo.com"
  status = 301

[[redirects]]
  from = "/pawblock"
  to = "https://www.pawblock.dannyguo.com"
  status = 301
