version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.41
    working_directory: /src
    steps:
      - checkout
      - run:
          name: Build the site
          command: hugo
      - run:
          name: Lint the HTML
          command: htmlproofer --check-favicon --check-html --check-opengraph --disable-external public
